acqs_models:
  - "uncnorm rwll"
  - "unc rwll"
  - "unc rwll0010"
  - "uncnorm rwll0010"
  - "uncnormdecaytau rwll0010"
  - "voptfull rwll0010"
  - "soptfull rwll0010"
  - "mcvopt rwll"
  - "random rwll"
  

acc_models:
  - "rwll"
  - "rwll0010"

seeds: [2, 3] #, 5, 6, 15, 16, 29, 30, 49, 50]
