acqs_models:
  - "uncnorm rwll"
  - "unc rwll"
  - "unc rwll0010"
  - "uncnorm rwll0010"
  - "uncnormdecaytau rwll0010"
  - "uncnormswitchK rwll0010"
  - "uncnormpropdecaytau rwll0010"
  - "uncnormprop rwll0010"
  - "uncnormpropswitchK rwll0010"
  - "uncnormprop++decaytau rwll0010"
  - "uncnormprop++ rwll0010"
  - "uncnormprop++switchK rwll0010"
  - "uncnormprop++decaytaukde rwll0010"
  - "uncnormprop++kde rwll0010"
  - "uncnormprop++switchKkde rwll0010"
  - "uncnormkde rwll0010"
  - "uncnormdecaytaukde rwll0010"
  - "voptfull rwll0100"
  - "mcvopt rwll"
  - "random rwll"
  

acc_models:
  - "rwll"
  - "rwll0010"

seeds: [2, 3, 5, 6, 15, 16, 29, 30, 49, 50]
