acqs_models:
  - "betavar beta0"
  - "betavar beta01"
  - "betavar beta1"
  - "uncnorm rwll01"
  - "uncsftmax poisson"
  - "uncdist rwll01"
  - "random poisson"
  

acc_models:
  - "beta0" 
  - "beta01"
  - "rwll01"
  - "poisson"

seeds: [2, 3, 5, 6, 14, 15, 29, 30, 50, 51]
